# Generated by Django 4.2.1 on 2023-06-09 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nomCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id del producto')),
                ('nomProducto', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion del producto')),
                ('precio', models.IntegerField(max_length=10, verbose_name='Precio del producto')),
                ('fechaCreacion', models.DateField(auto_now_add=True, verbose_name='Fecha creacion del producto')),
                ('fechaActualizacion', models.DateField(auto_now=True, verbose_name='Fecha de actualizacion del producto')),
                ('nomCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
