# Generated by Django 4.2.1 on 2023-06-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productos',
            old_name='nomCategoria',
            new_name='categoria',
        ),
        migrations.AlterField(
            model_name='productos',
            name='fechaActualizacion',
            field=models.DateTimeField(verbose_name='Fecha de actualizacion del producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='fechaCreacion',
            field=models.DateTimeField(verbose_name='Fecha creacion del producto'),
        ),
    ]
