# Generated by Django 4.2.1 on 2023-06-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_nomcategoria_productos_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='Ingrese Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Ingrese Apellido')),
                ('direccion', models.CharField(max_length=200, verbose_name='Ingrese direccion')),
                ('correo', models.EmailField(max_length=254, verbose_name='Ingrese correo electronico')),
                ('telefono', models.IntegerField(max_length=9, verbose_name='Ingrese numero telefono')),
            ],
        ),
        migrations.AlterField(
            model_name='productos',
            name='precio',
            field=models.IntegerField(verbose_name='Precio del producto'),
        ),
    ]
