# Generated by Django 4.2.1 on 2023-06-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cliente_alter_productos_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, verbose_name='Ingrese numero telefono'),
        ),
    ]
