# Generated by Django 4.2.1 on 2023-06-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trazabilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trazabilidad',
            name='accion',
            field=models.BooleanField(default=False, verbose_name='Acción realizada'),
        ),
    ]
